name: Run Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Change this to your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install streamlit

      - name: Run Streamlit app
        run: |
          nohup streamlit run app.py --server.headless true &
          sleep 10
          curl -I http://localhost:8501

      # Optionally: Add any test or health checks here